### ISSUE TITLE
Improve error handling in KeystoreTool.keyPairExists()

### ISSUE THREAD

**Issue by dhleong** [adorsys/secure-storage-android#42]
I can consistently reproduce a crash on my Pixel 3 by just clearing app storage and starting again. It appears the cause is a `ProviderException` caused (eventually) by a `KeyStoreException` with the message "Key not found." Currently, this exception is treated as a `KEYSTORE_EXCEPTION`-type exception, but I think this case should be handled safely and return `false` from `keyPairExists`. 

In this state, occasionally the app will eventually recover, but usually I just have to uninstall and reinstall. 

Here's a long stack trace:

```

     Caused by: java.security.ProviderException: Failed to load generated key pair from keystore
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:530)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:472)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
        at de.adorsys.android.securestoragelibrary.a.g(Unknown Source:92)
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:6) 
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:6) 
        at com.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:122) 
        at com.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68) 
        at com.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41) 
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36) 
        at io.reactivex.Completable.subscribe(Completable.java:2309) 
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.security.UnrecoverableKeyException: Failed to obtain information about key
        at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:242)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:308)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:521)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:472) 
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727) 
        at de.adorsys.android.securestoragelibrary.a.g(Unknown Source:92) 
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:6) 
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:6) 
        at com.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:122) 
        at com.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68) 
        at com.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41) 
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36) 
        at io.reactivex.Completable.subscribe(Completable.java:2309) 
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.security.KeyStoreException: Key not found
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1273)
        at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:244)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:308) 
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:521) 
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:472) 
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727) 
        at de.adorsys.android.securestoragelibrary.a.g(Unknown Source:92) 
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:6) 
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:6) 
        at com.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:122) 
        at com.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68) 
        at com.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41) 
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36) 
        at io.reactivex.Completable.subscribe(Completable.java:2309) 
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

Thoughts?

**Comment by luckyhandler** [comment]
Hi @dhleong , sounds reasonable. Thanks for the report - we'll keep you updated!

**Comment by dhleong** [comment]
Thank you!

**Comment by luckyhandler** [comment]
Hi @dhleong, I just pushed a fix for this issue in Commit https://github.com/adorsys/secure-storage-android/commit/3b1b37641f3e706ce253548ace0382297135024f
Feel free to have a look.

**Comment by luckyhandler** [comment]
We just released version 1.1.0 which contains your requested change. It fixes also another issue, why we had to change the api of the library

**Comment by dhleong** [comment]
Excellent, thanks! I'll give it a shot.

**Comment by dhleong** [comment]
I'm still getting a crash when I clear data. The trace is slightly different, though; I'll open a new ticket.
